src/components/diffviewermeta.js
src/style.css

Hi Armen,
I made a change about the fontsize of the numbers in the meta diffviewer area,
now they are bigger, and easier to view. Would you take a look at it?
Linkai

Make the fontsize of numbers in the meta diffviewer larger

---

src/components/diffviewer.js
src/utils/data.js

Under certain circumstances the coverage data can be
incorrect and we need to safe guard against it.

Issue #61 - fix: DiffViewer fails in certain changesets

---

package.json

Heroku builds properly the switch to Neutrino, however, for some reason the app won't start:
> Feb 09 05:45:35 firefox-code-coverage heroku/web.1: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch 
I've read that letting Heroku choose the LTS versions of node and npm helps with this issue.
Let's try it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/113)

Let Heroku choose the default LTS node, npm and yarn

---

src/components/diffviewer.js
src/style.css

… of files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/111)

Issue #85 - Add link to fileviewer in diffblocks to view a file's coverage

---

src/components/fileviewercov.js
src/utils/color.js
src/utils/data.js

Issue #79 - Move coverage percentage logic to coverage parse logic
Issue #79 - Move coverage percentage logic to coverage parse logic
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/124)

Issue #79 - Move coverage percentage logic to coverage parse logic

---

src/components/diffviewer.js

Fixes #120 
Previously coverage was determined by looking at the fileDiffs object when line coverage information was actually in fileDiffs.lines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/125)

Issue #120: Bad coverage calculation

---

src/components/summaryviewer.js
src/style.css

Changeset column links now redirect to Hg and Coverage Diff column created to access DiffViewer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/121)

Issue #107 - Changeset in main page to link to Hg and coverage summary to navigate to the diff viewer

---

src/components/fileviewer.js
src/settings.js
src/utils/data.js

#115 FileViewer should now load the Covered Tests sidebar correctly for revision numbers longer than 12 letters. An extra truncation was added to the revision number when querying ActiveData.
This shows the tests correctly
https://firefox-code-coverage.herokuapp.com/#/file?revision=fdd1a0082c71&path=js/src/wasm/WasmValidate.cpp
This fails to load tests from ActiveData currently, but loads correctly on my local
https://firefox-code-coverage.herokuapp.com/#/file?revision=fdd1a0082c71673239fc2f3a6a93de889c07a1be&path=js/src/wasm/WasmValidate.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/146)

Issue #115: FileViewer: Accept any length revision number

---

.neutrinorc.js
src/components/app.js
src/components/diffviewer.js
src/components/fileviewer.js
src/components/fileviewercov.js
src/components/summaryviewer.js
src/utils/data.js

Normally, from the SummaryViewer you should not be able to get to the DiffViewer since
there's no link to navigate to it.
However, people clicking on links from GitHub issues can reach the DiffViewer, thus,
failing because there `coverage` object contains a summary property rather than
being undefined.
This change shows an error message to the user letting them know that they should
try again later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/152)

Fix: The DiffViewer should not fail if the coverage data for a changeset is PENDING

---

src/containers/diffViewer.jsx
src/utils/coverage.js
src/utils/data.js
src/utils/hg.js
src/utils/localCache.js

This PR adds back caching the 'coverage' data for all changesets on the main view.
It also adds caching for individual changesets (there's room for improving the code) which is useful for the diff viewer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/161)

Increase caching range

---

src/components/coverageMeta.jsx

By default, HTML elements ignore and white-space characters like line breaks, causing bug descriptions to show up in a single, unbroken line. Adding the attribute `white-space: pre` fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/167)

Correctly display white-space in bug descriptions.

---

.neutrinorc.js
src/components/githubRibbon.jsx
src/settings.js
src/style.css

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/169)

Replace the pixelated GitHub ribbon with a nicer CSS version.

---

src/style.css

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/168)

Fix author placeholder icon margin.

---

README.md
src/settings.js

Maybe we want to wait a couple of days before doing this, since there are just a few revisions on https://codecov.io/github/mozilla/gecko-dev.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/171)

Update codecov.io and shipit URLs to point to production instances

---

src/components/changesetInfo.jsx
src/containers/diffViewer.jsx
src/utils/hg.js

We were not initalizing a changeset's metadata the same way as when fetched
as part of a call to jsonPushes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/173)

Calling getChangesetMeta() does not have author's email and name parsed

---

src/components/diffViewer.jsx
src/containers/diffViewer.jsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/187)
This PR fixes issue #135 which means it does not touch the main view but the diff viewer.
It seems that some of the recent changes landed has made this issue not as bad.
There's still a slight difference in behaviour:
* https://firefox-code-coverage.herokuapp.com/#/changeset/3cee5c02db0a065f081989d3e0514563aac355ab
* https://firefox-code-coverage-pr-187.herokuapp.com/#/changeset/3cee5c02db0a065f081989d3e0514563aac355ab
﻿﻿﻿The console, however, it is clean for the 2nd link.

Issue #135 - Protect against backend data not being available

---

src/containers/fileViewer.jsx

1. `git clone https://github.com/mozilla/firefox-code-coverage-frontend/ front && cd front`
2. `yarn install && yarn start`
3. Visit http://localhost:5000/#/file?revision=980d4dc65afc&path=mfbt/Assertions.cpp
4. Edit URL to http://localhost:5000/#/file?revision=980d4dc65afc&path=mfbt/ChaosMode.cpp and hit `Enter`
- The page should load + show the coverage data of `ChaosMode.cpp`
- Nothing happens (you need to hit `Cmd + R` to force a page reload and get the correct data)
This pull request fixes this by resetting the state when getting a `'hashchange'` event.
@armenzg please take a look.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/195)

File viewer: Support 'hashchange' navigation events

---

CONTRIBUTING.md
src/components/coverageMeta.jsx

I'm trying to add author information to the changeset coverage view, just like in the list of changesets on the front page.
However, for some reason, there is no `changeset.authorInfo` in the file I'm editing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/170)

Show patch author in DiffViewer.

---

src/components/diffLine.jsx
src/containers/diffViewer.jsx
src/containers/fileViewer.jsx
src/containers/summary.jsx
src/utils/coverage.js
src/utils/hg.js

Fix for #144 
- Removed logging to console
- Added generic `throw error` for catch blocks 
@armenzg please review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/196)

Issue #144: Added re-throwing of errors

---

src/components/routes.jsx
src/containers/fileViewer.jsx
src/utils/coverage.js

... by moving `revision` and `path` from state to props.
This is based on @armenzg's suggestion:
https://github.com/mozilla/firefox-code-coverage-frontend/pull/195#pullrequestreview-134378222
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/215)

Refactor FileViewerContainer.parseQueryParameters() away

---

README.md

Fixes #231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/235)

Specify that coverage data comes from Windows too

---

.travis.yml

This will hopefully clear up some of the linting errors that are only
happening on Travis CI.
Changes:
- Switch to Xenial since it is the latest Ubuntu LTS.
- Add 'lts" as one of the Node versions to test on
- Remove before_install for known old Yarn issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/247)

Few Travis CI changes
