mozilla/firefox-code-coverage-frontend

- src/components/diffviewermeta.js
Now, coverage percentage = covered_new_lines / total_new_lines (only count executable lines)
> issue number #36 - solve the wrong calculation of "new lines coverage percentage"

- README.md
- src/components/app.js
r? @jmaher @marco-c @klahnakoski
> Issue #44 - docs: Update app's disclaimers and documentation

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/95)
> Link to overall architecture of Mozilla's code coverage blog post

- CONTRIBUTING.md
This file helps contributors determine what steps to follow to better collaborate together.
r? @gmierz
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/94)
> Guide on how to contribute to the project

- src/components/summaryviewer.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/88)
> Issue 90 - Add bugzilla links to summary viewer

- src/components/diffviewer.js
- src/style.css
Repositioned and resized links in Diff Viewer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/93)
> WIP: Issue75 - Diffviewer, Reshuffle some links

- src/components/diffviewer.js
- src/utils/data.js
@jhkren let's use this
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/100)
> Issue #67 - Sort DiffViewer by file with least covered lines percentage

- src/components/summaryviewer.js
- src/settings.js
- src/style.css
Fixed Issue #21. Added Loading Functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/112)
> Fix #21 Add Loading Functionality

- package.json
- yarn.lock
@Dottori I don't know if this will fix forgetting to do `git add` but I believe it will improve some things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/131)
> Prevent commiting code without fixing linting issues first

- package.json
- src/components/summaryviewer.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/129)
> Issue #119 - Cache changesets for SummaryViewer

- package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/134)
> Issue #126 - Upgrade to parse-diff 0.4.2

- package.json
- src/index.jsx
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/140)
> Issue #139 - Use sentry.io to track frontend runtime issues

- .neutrinorc.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/142)
> Issue #141 - Generate source maps for production

- src/components/app.js
- src/style.css
Added GitHub ribbon to top right corner. Please review it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/145)
> Added GitHub ribbon

- .neutrinorc.js
- src/components/app.js
- src/components/diffviewer.js
- src/components/summaryviewer.js
- src/settings.js
- src/utils/data.js
- src/utils/fetch_data.js
- src/utils/hg.js
- src/utils/localCache.js
This will allow the DiffViewer to fetch information from hg.mozilla.org.
Right now the logic for Mercurial was 100% coupled with the ChangesetsViewer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/155)
> Move logic dealing with Hg into its own module

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/185)
> Run tests on Travis

- package.json
- src/components/diffFile.jsx
- src/style.css
- yarn.lock
r? @jankeromnes 
f? @calixteman @marco-c 
The deployment will show up in the next few minutes.
Meanwhile here's a screenshot:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/183)
> Issue #69 - Allow folding & unfolding of files in the diff view

- src/components/changesetFilter.jsx
- src/containers/summary.jsx
- src/style.css
This is useful if you want to see changesets associated to the
same bug.
f? @calixteman @marco-c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/184)
> Issue #56 - Allow filtering by changeset's description

- src/utils/coverage.js
This prevents the backend from showing as broken.
There's currently a DNS issue happening for the backend.
r? @jankeromnes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/189)
> Handle better if the backend is down

- src/components/errorBoundary.jsx
- src/components/genericErrorMessage.jsx
- src/containers/summary.jsx
- src/index.jsx
- src/settings.js
- src/utils/coverage.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/190)
> Better handle errors and fix some issues

- CONTRIBUTING.md
Fixes #233 
r? @marco-c @armenzg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/firefox-code-coverage-frontend/234)
> Fixes broken link to blog in contributing.md
